### ISSUE TITLE
content must be any not object

### ISSUE THREAD

**Issue by giuliohome** [jlguenego/angular-sso-example#32]
Please update this [line](https://github.com/jlguenego/angular-sso-example/blob/master/front/src/app/user.service.ts#L23) to:

```typescript
export class UserService {
  isConnected = false;
  content: any | undefined; // <-- here it must be any and not object !
  constructor(private http: HttpClient) {
    this.checkConnection();
  }
```

You can read more about Angular type system in their [blog](https://blog.angular-university.io/typescript-2-type-system-how-does-it-really-work-when-are-two-types-compatible-its-actually-quite-different-than-other-type-systems/).

**Comment by jlguenego** [comment]
Merged request. Please test.

**Comment by jlguenego** [comment]
Anyway the project should be more strict in fact. The content should be 'unknown'.
