### ISSUE TITLE
AcceptSecurityContext: SECURITY_STATUS incorrect

### ISSUE THREAD

**Issue by giuliohome** [jlguenego/angular-sso-example#33]
Today I have been getting this error ([cross-reference](https://github.com/jlguenego/node-expose-sspi/issues/33#issuecomment-678956256)) when calling node.js sso connection from another machine in my intranet.

AFAICS, the point is that the domain was sent together with the userid from the browser.

I have fixed it by clearing the default domain that the service was passing to the SSO (even if it was the same as the domain passed from the client in the userid).

My fix is, for example:

```typescript
  const credentials: UserCredential = {
    domain:'',
    user: req.body.login,
    password: req.body.password,
  };
```

at this server's [line](https://github.com/jlguenego/angular-sso-example/blob/master/back/src/server.ts#L64).

This Is partially superseded if one bumps the sspi version to the latest: depending on AD configuration (and based on the userid in the application pool in case of iisnode) I would derive the domain from the `split('\\')` of the login.

Of course, *among other things*, in order to get the Kerberos **SSO** ticket **automatically** from Win OS both Chrome and Edge browsers require the login server domain [to be configured](https://active-directory-wp.com/docs/Networking/Single_Sign_On/Configure_browsers_to_use_Kerberos.html) in the **Internet Explorer security settings** of local internet or *trusted sites*. (for GPO see [here](https://blog.thesysadmins.co.uk/group-policy-internet-explorer-security-zones.html))

**Comment by jlguenego** [comment]
merged.

**Comment by jlguenego** [comment]
Please test and close.
