### ISSUE TITLE
using this app from a different machine, not just localhost

### ISSUE THREAD

**Issue by giuliohome** [jlguenego/angular-sso-example#34]
If the Angular client is opened on a different machine - that is the classical scenario where the users from their machines are connected to a server located elsewhere in the intranet - you can't call the back end service using localhost.

Here is my fix

```typescript
const domainUrl = 'http://<server>:3500';
function getDomainUrl () {return domainUrl.replace('<server>',window.location.hostname);}
```

and of course I've also replaced all the `domainUrl` references with `getDomainUrl()`

**Comment by jlguenego** [comment]
Merged. Please test and close.
